# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import importlib.metadata

# Adding the directory to the PYTHONPATH (do not need it, use pip install -e. in .venv)
# import os
# import sys
# sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src")))

from MLGWSC_proposal import __version__, __name__ as __package_name__

# Get package metadata.
_metadata = importlib.metadata.metadata(__package_name__)   # from .toml file

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = __package_name__
author = _metadata["Author-email"]
copyright = f"2025-%Y, {author}"
version = __version__
release = version

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",       # Automatically generates documentation form docstrings
    "sphinx.ext.todo",
    "sphinx.ext.viewcode" ,      # Adds links to source code in the documentation
    "sphinx.ext.napoleon"      # For NumPy docstrings (VS Code automatically generates them)
]

autodoc_default_options = {     # Configurating the autodoc extension for the API
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "private-members": True
}

autodoc_typehints = "none"      # Shows type hints only in the docstring not in the firm
autodoc_typehints_format = "short"
todo_include_todos = True

# Options for syntax highlighting.
pygments_style = "default"
pygments_dark_style = "default"

# Options for internationalization.
language = "en"

# Options for markup.
rst_prolog = f"""
.. |Python| replace:: `Python <https://www.python.org/>`__
.. |Sphinx| replace:: `Sphinx <https://www.sphinx-doc.org/en/master/>`__
.. |numpy| replace:: `NumPy <https://numpy.org/>`__
.. |GitHub| replace:: `GitHub <https://github.com/>`__
"""

# Options for source files.
# Excludes these directories while searching for source code (mostly auto-generated by the OS)
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Options for templating.
templates_path = ["_templates"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# html_theme = "sphinxawesome_theme"
# html_theme_options = {
#     "awesome_external_links": True,
# }

html_theme = "pydata_sphinx_theme"

html_logo = "_static/logo_unipi.png"
html_favicon = "_static/logo_unipi.png"
html_permalinks_icon = "<span>#</span>"
html_static_path = ["_static"]              # Directory for icon and logo